# Generated by Django 3.0.8 on 2020-07-19 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_point_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image'], 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Места'},
        ),
    ]
