# Generated by Django 3.0.8 on 2020-07-19 08:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200719_0741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position'], 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='place',
            name='description_long_html',
            field=tinymce.models.HTMLField(default='default', verbose_name='Полное описание'),
            preserve_default=False,
        ),
    ]
